# Generated by Django 5.0.7 on 2024-08-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_login',
            field=models.BooleanField(default=False),
        ),
    ]
