# Generated by Django 5.0.7 on 2024-07-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('store', '0006_alter_variation_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='varaitions',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
