# Generated by Django 5.0.7 on 2024-07-29 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_varaitions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='varaitions',
            new_name='variations',
        ),
    ]
