# Generated by Django 5.0.7 on 2024-08-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
